version: '3'
services:
  nuxt-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_CONNECT_DOCKER}  # Variável de ambiente do .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M  # Definir um limite de memória

  mongo:
    image: mongo:6.0.4-focal
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

    restart: always

volumes:
  mongo-data:
